#### Broadcasting

In [5]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
c = a * b
print(c)

[2. 4. 6.]


In [6]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0])
c = a * b
print(c)

[2. 4. 6.]


### Vectorising

In [7]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [8]:
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

## Datalab Prep

In [9]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [3.14, 89, 400, 23, 1000, 657, 0]

In [10]:
def list_multiply(list_1, list_2):
    """
    Multiply two lists element-wise, handling unequal sizes.

    Parameters:
    - list_1 (list): The first input list.
    - list_2 (list): The second input list.

    Returns:
    - list: A new list containing the element-wise product of the input lists.
    """

    # Initialize an empty list to store the result
    list_result = []

    # Iterate over the common elements of the lists
    for element in range(min(len(list_1), len(list_2))):
        list_result.append(list_1[element] * list_2[element])

    # If list_1 is shorter, add the remaining elements of list_2
    for obj in range(len(list_1), len(list_2)):
        list_result.append(list_2[obj])

    return list_result

# Example usage
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 3, 4, 5, 6]
result = list_multiply(list_1, list_2)
print(result)

[3.14, 178, 1200, 92, 5000, 657, 0]

In [11]:
one = np.array(list_1)
two = np.array(list_2)
matrice = np.ones(7)
matrice[:5] = one
result = (two * matrice)
print(result)

[3.14e+00 1.78e+02 1.20e+03 9.20e+01 5.00e+03 6.57e+02 0.00e+00]


In [12]:
def np_list_multiply(list_1, list_2):
    # Convert lists to NumPy arrays
    one = np.array(list_1)
    two = np.array(list_2)
    
    # Perform element-wise multiplication
    result = one * two
    return result

# Example usage
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 3, 4, 5, 6]

result = np_list_multiply(list_1, list_2)
print(result)

[ 2  6 12 20 30]


Time the two functions and comment on the improvements you observe in speed.

In [13]:
import timeit
import numpy as np

# Function using NumPy
def np_list_multiply(list_1, list_2):
    one = np.array(list_1)
    two = np.array(list_2)
    result = one * two
    return result

# Function using loops
def list_multiply(list_1, list_2):
    list_result = []
    for element in range(min(len(list_1), len(list_2))):
        list_result.append(list_1[element] * list_2[element])
    for obj in range(len(list_1), len(list_2)):
        list_result.append(list_2[obj])
    return list_result

# Example lists
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 3, 4, 5, 6]

# Time the NumPy function
time_np = timeit.timeit(lambda: np_list_multiply(list_1, list_2), number=1000000)

# Time the function using loops
time_loop = timeit.timeit(lambda: list_multiply(list_1, list_2), number=1000000)

# Print the results
print(f"NumPy function time: {time_np} seconds")
print(f"Function using loops time: {time_loop} seconds")

NumPy function time: 1.6521314580459148 seconds
Function using loops time: 0.7265508340205997 seconds
