## Assignment: Elementary Operations on Matrices

In [1]:
import numpy as np

### I. Verifying matrix operations

#### 1. Compute the transpose of the following matrices by hand:

In [2]:
A1 = np.array([[3, -5], [-2, 7]])
B1 = np. array ([[2, -3, 4], 
                [-5, 6, 7],
                [-8, 9 ,1]])
print(f'Transpose of A is: \n{np.transpose(A1)}','\n'f'Transpose of B is: \n{np.transpose(B1)}')

Transpose of A is: 
[[ 3 -2]
 [-5  7]] 
Transpose of B is: 
[[ 2 -5 -8]
 [-3  6  9]
 [ 4  7  1]]


#### 2. Consider the following two matrices:

In [14]:
A2 = np.array([[3, 2, -1],
               [-2, 7, 4],
               [1, 6, 8]])
B2 = np.array([[2, -3, -4],
               [-5, -6, 7],
               [-8, 9, 1]])

Compute the element-wise product of matrices 

In [15]:
print(A2 * B2)

[[  6  -6   4]
 [ 10 -42  28]
 [ -8  54   8]]


Compute the matrix product of matrices 

In [16]:
print(A2@B2)

[[  4 -30   1]
 [-71   0  61]
 [-92  33  46]]


Now, change the order of the matrices and compute the element-wise and matrix products again

- Element-wise product:

In [17]:
print(B2*A2)

[[  6  -6   4]
 [ 10 -42  28]
 [ -8  54   8]]


- Matrix product:

In [18]:
print(B2@A2)

[[  8 -41 -46]
 [  4 -10  37]
 [-41  53  52]]


#### 3. Consider the following matrices:

In [34]:
A3 = np.array([[3, 2, -1],
               [-2, 7, 4],
               [1, 6, 8]])
B3 = np.array([[3, -2, 1],
               [2, 7, 6],
               [-1, 4, 8]])
C1 = np.array([[1, 3, 5],
              [2, 6, 7],
              [4, 12, 8]])

Compute the determinant of the matrices:

In [7]:
print(np.lookfor("determinant"))

Search results for 'determinant'
--------------------------------
numpy.linalg.det
    Compute the determinant of an array.
numpy.linalg.slogdet
    Compute the sign and (natural) logarithm of the determinant of an array.
numpy.vander
    Generate a Vandermonde matrix.
numpy.linalg.qr
    Compute the qr factorization of a matrix.
numpy.ma.vander
    Generate a Vandermonde matrix.
numpy.linalg._umath_linalg.slogdet
    slogdet on the last two dimensions and broadcast on the rest.
None


In [11]:
print(f"det(A): {int(np.linalg.det(A3))}",'\n'
      f"det(B): {int(np.linalg.det(B3))}",'\n'
      f'det(C): {int(np.linalg.det(C1))}')

det(A): 155 
det(B): 155 
det(C): 0


### 4. Consider the following matrices:

In [12]:
A4 = np.array([[3, 2], [2, 7]])
B4 = np.array([[4, 0], [0, 5]])

Compute the inverse of matrices:

In [22]:
A_inv = np.linalg.inv(A4).round(decimals=2)
B_inv= np.linalg.inv(B4)
print(f'A(-1): \n{A_inv}','\n'
      f'B(-1): \n{B_inv}')

A(-1): 
[[ 0.41 -0.12]
 [-0.12  0.18]] 
B(-1): 
[[0.25 0.  ]
 [0.   0.2 ]]


Verify that A(-1) x B(-1) = (B x A)(-1) (consider the matrix multiplication).

In [33]:
if (A_inv@B_inv).any() == np.linalg.inv(B4@A4).any():
    print(f"Relationship true.\n(Inverse of A) * (Inverse of B) is:\n{A_inv@B_inv}.\nInverse of B * A is:\n{np.linalg.inv(B4@A4)}")

Relationship true.
(Inverse of A) * (Inverse of B) is:
[[ 0.1025 -0.024 ]
 [-0.03    0.036 ]].
Inverse of B * A is:
[[ 0.10294118 -0.02352941]
 [-0.02941176  0.03529412]]


### II. Matrix properties

Consider the following matrices and scalars:

In [75]:
A = np.array([[3, 2, -1],
              [-2, 7, 4],
              [1, 6, 8]])
B = np.array([[-1, 2, 3],
              [5, -4, 9],
              [-7, 8, 6]])
C = np.array([[-5, 4, 9],
              [6, 1, 3],
              [7, 2, -8]])
alpha = 2
beta = 3

Verify the following properties:

In [40]:
if (A.T).T.any() == A.any():
    print(f'True.\nTranspose of A is:\n{A.T}.\nTranspose of transpose is\n{A.T.T}')

True.
Transpose of A is:
[[ 3 -2  1]
 [ 2  7  6]
 [-1  4  8]].
Transpose of transpose is
[[ 3  2 -1]
 [-2  7  4]
 [ 1  6  8]]


In [42]:
if (A + B).any() == (B + A).any():
    print(f'True.\nA + B = B + A')        

True.
A + B = B + A


In [43]:
if (A + (B + C)).any() == ((A + B) + C).any():
    print('True.\nA + (B + C) == (A + B) + C')

True.
A + (B + C) == (A + B) + C


In [45]:
if (A + B).T.any() == (A.T + B.T).any():
    print('True.\nTranspose of (A + B) is equal to the sum of the transpose of each matrix')

True.
Transpose of (A + B) is equal to the sum of the transpose of each matrix


In [54]:
if (A@B) is not (B@A):
    print("True.\nMatrices are not commutative")

True.
Matrices are not commutative


In [55]:
if (A@(B@C)) is not ((A@B)@C):
    print('True.\nMatrices are not associative')

True.
Matrices are not associative


In [57]:
if (A@(B + C)).any() == (A@B + A@C).any():
    print('True.\nMatrices are distributive')

True.
Matrices are distributive


In [60]:
if (A@B).T.any() is (B.T@A.T).any():
    print('True.\nTranspose of A*B is (B transposed * A transposed)')

True.
Transpose of A*B is (B transposed * A transposed)


In [64]:
if np.linalg.inv(A@B).any() is (np.linalg.inv(B)@np.linalg.inv(A)).any():
    print("True.\nInverse of A * B is equal to the produce of the inverses.")

True.
Inverse of A * B is equal to the produce of the inverses.



In [65]:
if np.linalg.inv(A.T).any() is (np.linalg.inv(A).T).any():
    print('True.\nThe inverse of the transposed is the transpose of the inverse')

True.
The inverse of the transposed is the transpose of the inverse


In [70]:
if ((alpha + beta)*A).any() is (alpha * A + beta *A).any():
    print('True.\n(Alph + Beta) * A = Alph * A + Beta * A)')

True.
(Alph + Beta) * A = Alph * A + Beta * A)


In [72]:
if (alpha * (A + B)).any() is (alpha * A + alpha*B).any():
    print('True.\nAlph * (A + B) = Alph * A + Alph * B)')

True.
Alph * (A + B) = Alph * A + Alph * B)


In [81]:
if (np.linalg.inv(alpha * A)).any() is (0.5 * np.linalg.inv(A)).any():
    print('True.\nThe inverse of a produce between a scalar and a matrix is equal to the produce of the inverse of the scalar and the inverse of the matrix')

True.
The inverse of a produce between a scalar and a matrix is equal to the produce of the inverse of the scalar and the inverse of the matrix
